import { DossierSummary, DossierListItem } from '@/types/dossier';
import { EvidenceItem } from '@/types/evidence';
import { Finding } from '@/types/finding';

/**
 * ============================================================================
 * BENCHMARK DATASET FIXTURES FOR AUDITOR FORENSIC CONSOLE
 * ============================================================================
 * PROVENANCE: SYNTHETIC / CONTROLLED_CAPTURE
 * 
 * CRITICAL RULE:
 * Never present synthetic or simulated data as real municipal evidence.
 * These records support offline evaluation and UI verification across
 * the three canonical benchmark cases:
 *   1. SUBSTANTIVE_INCONSISTENCY
 *   2. CLEAN_COMPLIANT
 *   3. INCONCLUSIVE_DATA
 * ============================================================================
 */

export const BENCHMARK_DOSSIER_LIST: DossierListItem[] = [
  {
    id: 'DOSSIER-BLR-2026-W09-042',
    claimNumber: 'RA-BILL/2026/03/42',
    wardNumber: 'Ward 09 (Vidyaranyapura)',
    workOrderNumber: 'WO-SWD-9021',
    contractorName: 'Cauvery Infra & Desilting Services Ltd.',
    financialExposureInr: 1820000,
    arpiScore: 84,
    priorityTier: 'P1_CRITICAL',
    ecsScore: 0.42,
    status: 'SUBSTANTIVE_INCONSISTENCY',
    benchmarkCase: 'SUBSTANTIVE_INCONSISTENCY',
    submittedAt: '2026-03-12T10:30:00Z',
  },
  {
    id: 'DOSSIER-BLR-2026-W14-018',
    claimNumber: 'RA-BILL/2026/02/18',
    wardNumber: 'Ward 14 (Yelahanka)',
    workOrderNumber: 'WO-SWD-7714',
    contractorName: 'Karnataka Urban Works Corp.',
    financialExposureInr: 850000,
    arpiScore: 12,
    priorityTier: 'P4_ROUTINE',
    ecsScore: 0.96,
    status: 'VERIFIED_COMPLIANT',
    benchmarkCase: 'CLEAN_COMPLIANT',
    submittedAt: '2026-03-10T14:15:00Z',
  },
  {
    id: 'DOSSIER-BLR-2026-W22-099',
    claimNumber: 'RA-BILL/2026/03/99',
    wardNumber: 'Ward 22 (Hebbal)',
    workOrderNumber: 'WO-SWD-4482',
    contractorName: 'Nandi Drainage Solutions LLP',
    financialExposureInr: 1200000,
    arpiScore: 55,
    priorityTier: 'P2_HIGH',
    ecsScore: 0.61,
    status: 'PENDING_AUDIT',
    benchmarkCase: 'INCONCLUSIVE_DATA',
    submittedAt: '2026-03-14T09:00:00Z',
  },
];

export const BENCHMARK_DOSSIERS: Record<string, DossierSummary> = {
  'DOSSIER-BLR-2026-W09-042': {
    id: 'DOSSIER-BLR-2026-W09-042',
    claimNumber: 'RA-BILL/2026/03/42',
    contractor: {
      contractorId: 'CON-KA-5829',
      contractorName: 'Cauvery Infra & Desilting Services Ltd.',
      contractNumber: 'BBMP/SWD/2025-26/PKG-09B',
      workOrderNumber: 'WO-SWD-9021',
      workOrderDate: '2026-01-15',
      sanctionedAmountInr: 4850000,
      wardNumber: 'Ward 09 (Vidyaranyapura)',
      reachName: 'Primary Storm-Water Drain Reach 2 (Ch: 1200m to 2400m)',
      drainId: 'SWD-BLR-NZ-09-02',
    },
    financialExposureInr: 1820000,
    ecsScore: 0.42,
    arpiScore: 84,
    priorityTier: 'P1_CRITICAL',
    benchmarkCase: 'SUBSTANTIVE_INCONSISTENCY',
    status: 'SUBSTANTIVE_INCONSISTENCY',
    maxSeverity: 'CRITICAL',
    evidenceCounts: {
      photos: 6,
      receipts: 4,
      trips: 8,
      documents: 2,
    },
    unresolvedFindingsCount: 3,
    submittedAt: '2026-03-12T10:30:00Z',
  },
  'DOSSIER-BLR-2026-W14-018': {
    id: 'DOSSIER-BLR-2026-W14-018',
    claimNumber: 'RA-BILL/2026/02/18',
    contractor: {
      contractorId: 'CON-KA-3310',
      contractorName: 'Karnataka Urban Works Corp.',
      contractNumber: 'BBMP/SWD/2025-26/PKG-14A',
      workOrderNumber: 'WO-SWD-7714',
      workOrderDate: '2026-01-20',
      sanctionedAmountInr: 2200000,
      wardNumber: 'Ward 14 (Yelahanka)',
      reachName: 'Secondary SWD Reach 1 (Ch: 0m to 850m)',
      drainId: 'SWD-BLR-NZ-14-01',
    },
    financialExposureInr: 850000,
    ecsScore: 0.96,
    arpiScore: 12,
    priorityTier: 'P4_ROUTINE',
    benchmarkCase: 'CLEAN_COMPLIANT',
    status: 'VERIFIED_COMPLIANT',
    maxSeverity: 'CLEAN',
    evidenceCounts: {
      photos: 4,
      receipts: 2,
      trips: 4,
      documents: 1,
    },
    unresolvedFindingsCount: 0,
    submittedAt: '2026-03-10T14:15:00Z',
  },
  'DOSSIER-BLR-2026-W22-099': {
    id: 'DOSSIER-BLR-2026-W22-099',
    claimNumber: 'RA-BILL/2026/03/99',
    contractor: {
      contractorId: 'CON-KA-9912',
      contractorName: 'Nandi Drainage Solutions LLP',
      contractNumber: 'BBMP/SWD/2025-26/PKG-22C',
      workOrderNumber: 'WO-SWD-4482',
      workOrderDate: '2026-02-01',
      sanctionedAmountInr: 3100000,
      wardNumber: 'Ward 22 (Hebbal)',
      reachName: 'Hebbal Feeder Drain Reach 3 (Ch: 500m to 1600m)',
      drainId: 'SWD-BLR-NZ-22-03',
    },
    financialExposureInr: 1200000,
    ecsScore: 0.61,
    arpiScore: 55,
    priorityTier: 'P2_HIGH',
    benchmarkCase: 'INCONCLUSIVE_DATA',
    status: 'PENDING_AUDIT',
    maxSeverity: 'INCONCLUSIVE',
    evidenceCounts: {
      photos: 3,
      receipts: 3,
      trips: 5,
      documents: 1,
    },
    unresolvedFindingsCount: 1,
    submittedAt: '2026-03-14T09:00:00Z',
  },
};

export const BENCHMARK_EVIDENCE: Record<string, EvidenceItem[]> = {
  'DOSSIER-BLR-2026-W09-042': [
    {
      id: 'EV-PHOTO-001',
      dossierId: 'DOSSIER-BLR-2026-W09-042',
      type: 'SITE_PHOTO',
      title: 'Pre-Desilting Site Photo - Reach 2 Ch: 1450m',
      description: 'Upstream view of silt accumulation before desilting work commenced.',
      provenance: 'SYNTHETIC',
      submittedAt: '2026-02-10T09:15:00Z',
      fileUrl: '/fixtures/photo_pre_001.jpg',
      mimeType: 'image/jpeg',
      sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      metadata: {
        camera: 'Samsung Galaxy A52',
        focalLength: '5.2mm',
        shutterSpeed: '1/250s',
      },
      epistemicInfo: {
        category: 'FACT',
        sourceRef: 'EXIF Metadata & Site Camera Upload',
        timestamp: '2026-02-10T09:15:00Z',
      },
    },
    {
      id: 'EV-PHOTO-002',
      dossierId: 'DOSSIER-BLR-2026-W09-042',
      type: 'SITE_PHOTO',
      title: 'Post-Desilting Site Photo - Reach 2 Ch: 1450m (Instance Copy)',
      description: 'Post-desilting cleared drain bed submitted with RA Bill 42. Verified duplicate of Ward 07 Bill 19.',
      provenance: 'SYNTHETIC',
      submittedAt: '2026-02-28T16:20:00Z',
      fileUrl: '/fixtures/photo_post_002.jpg',
      mimeType: 'image/jpeg',
      sha256Hash: 'a7b1c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b999',
      metadata: {
        camera: 'Samsung Galaxy A52',
      },
      visualForensics: {
        candidatePhotoUrl: '/fixtures/photo_ward07_0819.jpg',
        candidateDossierId: 'DOSSIER-BLR-2025-W07-019',
        candidateWorkOrder: 'WO-SWD-6104',
        sscdSimilarity: 0.964,
        ransacInliers: 42,
        similarityThreshold: 0.82,
        inlierThreshold: 25,
        correspondenceVerified: true,
        candidateTimestamp: '2025-08-19T14:10:00Z',
        candidateGps: { lat: 13.0452, lng: 77.5819 },
      },
      epistemicInfo: {
        category: 'MODEL_OUTPUT',
        sourceRef: 'SSCD ResNet50 + SIFT/RANSAC Geometric Verification',
        confidence: 0.98,
        timestamp: '2026-02-28T16:20:00Z',
      },
    },
    {
      id: 'EV-RECEIPT-001',
      dossierId: 'DOSSIER-BLR-2026-W09-042',
      type: 'WEIGHBRIDGE_RECEIPT',
      title: 'Mavallipura Landfill Weighbridge Slip #78102',
      description: 'Thermal weighbridge slip for silt disposal truck KA-04-E-9102.',
      provenance: 'SYNTHETIC',
      submittedAt: '2026-02-20T14:45:00Z',
      fileUrl: '/fixtures/receipt_78102.pdf',
      mimeType: 'application/pdf',
      sha256Hash: 'c8d2c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b111',
      metadata: {},
      extractedData: {
        ticketNumber: 'WB-78102',
        vehicleNumber: 'KA-04-E-9102',
        grossWeightKg: 28400,
        tareWeightKg: 10200,
        netWeightKg: 18200,
        calculatedNetKg: 18200,
        arithmeticValid: true,
        timestamp: '2026-02-20 14:12:00',
        weighbridgeName: 'Mavallipura Landfill Public Weighbridge',
        ocrConfidence: 0.94,
      },
      pagination: {
        totalPages: 3,
        processedPages: [1],
        unprocessedPages: [2, 3],
        preservationGapNote: 'Multi-page PDF: Synchronous path processed Page 1; Pages 2-3 unrendered in current frozen Alpha backend.',
      },
      boundingBoxes: [
        {
          fieldKey: 'ticket_number',
          fieldLabel: 'Ticket #',
          value: 'WB-78102',
          confidence: 0.96,
          box: [0.12, 0.25, 0.16, 0.55],
        },
        {
          fieldKey: 'vehicle_number',
          fieldLabel: 'Vehicle #',
          value: 'KA-04-E-9102',
          confidence: 0.95,
          box: [0.22, 0.25, 0.26, 0.65],
        },
        {
          fieldKey: 'gross_weight',
          fieldLabel: 'Gross Weight',
          value: '28,400 kg',
          confidence: 0.96,
          box: [0.38, 0.55, 0.42, 0.85],
        },
        {
          fieldKey: 'tare_weight',
          fieldLabel: 'Tare Weight (Degraded)',
          value: '10,?00 kg',
          confidence: 0.48,
          isAmbiguous: true,
          box: [0.46, 0.55, 0.50, 0.85],
        },
        {
          fieldKey: 'net_weight',
          fieldLabel: 'Net Weight',
          value: '18,200 kg',
          confidence: 0.94,
          box: [0.54, 0.55, 0.58, 0.85],
        },
        {
          fieldKey: 'timestamp',
          fieldLabel: 'Slip Timestamp',
          value: '2026-02-20 14:12:00',
          confidence: 0.91,
          box: [0.68, 0.25, 0.72, 0.75],
        },
      ],
      epistemicInfo: {
        category: 'MODEL_OUTPUT',
        sourceRef: 'OCR Extracted from Document Artifact (AWS Textract)',
        confidence: 0.94,
        timestamp: '2026-02-20T14:12:00Z',
      },
    },
    {
      id: 'EV-TRIP-001',
      dossierId: 'DOSSIER-BLR-2026-W09-042',
      type: 'VEHICLE_TRIP',
      title: 'GPS Log: Truck KA-04-E-9102 (Trip 14)',
      description: 'Telematics trajectory from SWD Reach 2 excavation point to Mavallipura quarry.',
      provenance: 'SYNTHETIC',
      submittedAt: '2026-02-20T15:30:00Z',
      fileUrl: '/fixtures/trip_ka04e9102_14.json',
      mimeType: 'application/json',
      sha256Hash: 'b5e4c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b777',
      metadata: {},
      tripData: {
        vehicleNumber: 'KA-04-E-9102',
        startLocation: { lat: 13.0827, lng: 77.5582 },
        endLocation: { lat: 13.1492, lng: 77.5341 },
        distanceKm: 11.4,
        durationMinutes: 38,
        averageSpeedKmH: 18.0,
        tripTimestamp: '2026-02-20T14:48:22Z',
        reachStationing: {
          drainId: 'SWD-BLR-NZ-09-02',
          startChainageM: 1200,
          endChainageM: 2400,
        },
        bufferValidation: {
          drainBufferMeters: 50,
          disposalQuarryRadiusMeters: 500,
          isWithinBuffer: true,
        },
      },
      epistemicInfo: {
        category: 'FACT',
        sourceRef: 'Vehicle Telematics Unit (VTU) Ingestion',
        timestamp: '2026-02-20T14:48:22Z',
      },
    },
  ],
  'DOSSIER-BLR-2026-W14-018': [
    {
      id: 'EV-PHOTO-101',
      dossierId: 'DOSSIER-BLR-2026-W14-018',
      type: 'SITE_PHOTO',
      title: 'Pre-Desilting Photo - Reach 1 Ch: 200m',
      description: 'Pre-work channel profile showing silt accumulation.',
      provenance: 'SYNTHETIC',
      submittedAt: '2026-01-22T10:00:00Z',
      mimeType: 'image/jpeg',
      sha256Hash: 'f4e2c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b123',
      metadata: {},
      epistemicInfo: {
        category: 'FACT',
        sourceRef: 'Site Camera Upload',
        timestamp: '2026-01-22T10:00:00Z',
      },
    },
    {
      id: 'EV-RECEIPT-101',
      dossierId: 'DOSSIER-BLR-2026-W14-018',
      type: 'WEIGHBRIDGE_RECEIPT',
      title: 'Mavallipura Weighbridge Slip #66109',
      description: 'Thermal receipt with complete optical clarity and exact arithmetic.',
      provenance: 'SYNTHETIC',
      submittedAt: '2026-02-05T12:00:00Z',
      mimeType: 'application/pdf',
      sha256Hash: '98d2c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b456',
      metadata: {},
      extractedData: {
        ticketNumber: 'WB-66109',
        vehicleNumber: 'KA-04-E-5511',
        grossWeightKg: 24000,
        tareWeightKg: 9500,
        netWeightKg: 14500,
        calculatedNetKg: 14500,
        arithmeticValid: true,
        timestamp: '2026-02-05 11:30:00',
        weighbridgeName: 'Mavallipura Landfill Public Weighbridge',
        ocrConfidence: 0.97,
      },
      pagination: {
        totalPages: 1,
        processedPages: [1],
        unprocessedPages: [],
      },
      boundingBoxes: [
        {
          fieldKey: 'gross_weight',
          fieldLabel: 'Gross Weight',
          value: '24,000 kg',
          confidence: 0.98,
          box: [0.38, 0.55, 0.42, 0.85],
        },
        {
          fieldKey: 'tare_weight',
          fieldLabel: 'Tare Weight',
          value: '9,500 kg',
          confidence: 0.97,
          box: [0.46, 0.55, 0.50, 0.85],
        },
        {
          fieldKey: 'net_weight',
          fieldLabel: 'Net Weight',
          value: '14,500 kg',
          confidence: 0.98,
          box: [0.54, 0.55, 0.58, 0.85],
        },
      ],
      epistemicInfo: {
        category: 'MODEL_OUTPUT',
        sourceRef: 'OCR Extracted from Document Artifact',
        confidence: 0.97,
        timestamp: '2026-02-05T11:30:00Z',
      },
    },
  ],
  'DOSSIER-BLR-2026-W22-099': [
    {
      id: 'EV-RECEIPT-201',
      dossierId: 'DOSSIER-BLR-2026-W22-099',
      type: 'WEIGHBRIDGE_RECEIPT',
      title: 'Hebbal Quarry Weighbridge Slip #89112 (Faded)',
      description: 'Heavily faded thermal receipt scan. Tare and Gross weights below confidence threshold.',
      provenance: 'SYNTHETIC',
      submittedAt: '2026-02-15T16:00:00Z',
      mimeType: 'application/pdf',
      sha256Hash: '11d2c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b789',
      metadata: {},
      extractedData: {
        ticketNumber: 'WB-89112',
        vehicleNumber: 'KA-04-E-1209',
        grossWeightKg: 26000,
        tareWeightKg: 10000,
        netWeightKg: 16000,
        ocrConfidence: 0.44,
      },
      pagination: {
        totalPages: 2,
        processedPages: [1],
        unprocessedPages: [2],
        preservationGapNote: 'Page 1 evaluated; Page 2 unrendered.',
      },
      boundingBoxes: [
        {
          fieldKey: 'gross_weight',
          fieldLabel: 'Gross Weight (Faded)',
          value: '26,?00 kg',
          confidence: 0.44,
          isAmbiguous: true,
          box: [0.38, 0.55, 0.42, 0.85],
        },
        {
          fieldKey: 'tare_weight',
          fieldLabel: 'Tare Weight (Faded)',
          value: '10,?00 kg',
          confidence: 0.41,
          isAmbiguous: true,
          box: [0.46, 0.55, 0.50, 0.85],
        },
      ],
      epistemicInfo: {
        category: 'MODEL_OUTPUT',
        sourceRef: 'AWS Textract + Local Gating',
        confidence: 0.44,
        timestamp: '2026-02-15T16:00:00Z',
      },
    },
  ],
};

export const BENCHMARK_FINDINGS: Record<string, Finding[]> = {
  'DOSSIER-BLR-2026-W09-042': [
    {
      id: 'FINDING-W09-001',
      dossierId: 'DOSSIER-BLR-2026-W09-042',
      title: 'Visual Instance Copy: Reused Post-Desilting Photograph',
      description: 'Post-desilting photo EV-PHOTO-002 matches prior work photo from Ward 07 Bill 19 with 96.4% SSCD feature similarity and verified geometric keypoint alignment (42 inliers).',
      category: 'MODEL_OUTPUT',
      severity: 'CRITICAL',
      modality: 'VISUAL_VERIFICATION',
      gagas: {
        criteria: 'KPWD Specification & Contract Clause 14.2 requires original, contemporaneous photographic evidence captured at the contracted reach.',
        condition: 'Submitted photograph EV-PHOTO-002 possesses a 96.4% SSCD embedding similarity and 42 RANSAC geometric inliers matching Ward 07 Bill 19 (taken 6 months prior).',
        causeHypothesis: 'Contractor reused photographic records from an earlier desilting contract rather than capturing fresh post-work photographs.',
        effect: 'Disallows photographic verification of silt clearance, exposing INR 18.2 Lakhs in claimed payment to substantive evidentiary contestation.',
        recommendation: 'Withhold billing certification for Reach 2; issue immediate notice for primary uncompressed camera originals with complete EXIF tags.',
      },
      causality: {
        evidenceIds: ['EV-PHOTO-002'],
        extractedFacts: [
          {
            label: 'Submitted Image Hash',
            value: 'SHA-256: a7b1c442...b999',
            sourceRef: 'EV-PHOTO-002',
          },
          {
            label: 'Historical Match Reference',
            value: 'Ward 07 Bill 19 / EV-PHOTO-2025-0819',
            sourceRef: 'Historical S3 Repository',
          },
        ],
        modelOutputs: [
          {
            modelName: 'SSCD ResNet50 (512-d)',
            outputKey: 'Cosine Similarity',
            score: 0.964,
            confidence: 0.98,
            caveat: 'Candidate retrieved via pgvector HNSW index (threshold: 0.82)',
          },
          {
            modelName: 'SIFT + RANSAC Geometric Verification',
            outputKey: 'Inlier Keypoints',
            score: 42,
            confidence: 0.95,
            caveat: 'Homography matrix verified with 42 inliers (minimum threshold: 25)',
          },
        ],
        ruleResults: [
          {
            ruleId: 'RULE-IMG-001',
            ruleName: 'Cross-Claim Photo Uniqueness Constraint',
            passed: false,
            expected: 'Unique image across all municipal public-works dossiers',
            actual: 'Duplicate instance of prior work in Ward 07',
            deviation: 'Duplicate photo reuse',
          },
        ],
        inferences: [
          {
            statement: 'Post-desilting evidence photo is non-original and reused from an earlier contract.',
            basis: 'High SSCD embedding match corroborated by 42 geometric keypoint inliers.',
          },
        ],
        uncertaintyScore: 0.05,
        recommendedHumanAction: 'Flag for physical site inspection; request primary uncompressed camera originals with complete EXIF tags.',
      },
      createdAt: '2026-03-12T10:35:12Z',
    },
    {
      id: 'FINDING-W09-002',
      dossierId: 'DOSSIER-BLR-2026-W09-042',
      title: 'Temporal Contradiction: Vehicle Weighed Before Physical Arrival',
      description: 'Weighbridge ticket timestamp (14:12) precedes vehicle arrival at disposal weighbridge recorded by GPS telematics (14:48) by 36 minutes.',
      category: 'RULE_RESULT',
      severity: 'HIGH',
      modality: 'CROSS_MODAL',
      gagas: {
        criteria: 'Physical causality invariant: A vehicle cannot be weighed at a disposal facility before physical arrival at the weighbridge scale.',
        condition: 'Weighbridge ticket #78102 records weighing at 14:12:00 IST. Vehicle VTU telematics log confirms arrival at weighbridge perimeter at 14:48:22 IST.',
        causeHypothesis: 'Weighbridge slip may have been generated prematurely or vehicle telematics unit clock was out of synchronization.',
        effect: 'Uncertainty regarding validity of trip 14 silt disposal weight, totaling 18,200 kg net silt.',
        recommendation: 'Cross-verify weighbridge facility entry gate register and CCTV footage for 2026-02-20 between 14:00 and 15:00.',
      },
      causality: {
        evidenceIds: ['EV-RECEIPT-001', 'EV-TRIP-001'],
        extractedFacts: [
          {
            label: 'Ticket Timestamp',
            value: '2026-02-20 14:12:00 IST',
            sourceRef: 'EV-RECEIPT-001 (Slip #78102)',
          },
          {
            label: 'Vehicle GPS Arrival',
            value: '2026-02-20 14:48:22 IST',
            sourceRef: 'EV-TRIP-001 (VTU Log)',
          },
        ],
        modelOutputs: [
          {
            modelName: 'AWS Textract + Local Verification',
            outputKey: 'Ticket Timestamp Confidence',
            score: 0.94,
            confidence: 0.94,
          },
        ],
        ruleResults: [
          {
            ruleId: 'RULE-TIME-003',
            ruleName: 'Temporal Sequence: Vehicle Arrival Before Weighing',
            passed: false,
            expected: 'Vehicle Arrival Time <= Weighbridge Ticket Time',
            actual: 'Arrival (14:48) occurred 36 minutes AFTER Ticket Time (14:12)',
            deviation: '-36 minutes sequence inversion',
          },
        ],
        inferences: [
          {
            statement: 'Truck was weighed before physical arrival at the weighbridge according to GPS record.',
            basis: 'Direct deterministic contradiction between telematics log and ticket timestamp.',
          },
        ],
        uncertaintyScore: 0.12,
        recommendedHumanAction: 'Cross-verify weighbridge CCTV logs or request manual gate register entries for 2026-02-20.',
      },
      createdAt: '2026-03-12T10:35:15Z',
    },
    {
      id: 'FINDING-W09-003',
      dossierId: 'DOSSIER-BLR-2026-W09-042',
      title: 'Inconclusive Net Weight: Thermal Paper Tare Degradation',
      description: 'Weighbridge tare weight field partially degraded on thermal paper; OCR confidence 0.48 requires manual verification before certifying payment.',
      category: 'FACT',
      severity: 'INCONCLUSIVE',
      technicalState: 'INCONCLUSIVE_DATA',
      modality: 'DOCUMENT_INTELLIGENCE',
      gagas: {
        criteria: 'BBMP Public Works Manual Section 8.4 mandates verified Gross, Tare, and Net weighbridge documentation with optical clarity >= 0.75.',
        condition: 'Tare weight field on slip #78102 exhibits thermal fading, resulting in OCR confidence of 0.48 (below 0.75 threshold).',
        causeHypothesis: 'Thermal printer ribbon degradation or improper paper storage exposed to direct sunlight.',
        effect: 'Autonomous validation cannot confirm whether tare weight is 10,200 kg or 10,700 kg, affecting net silt tonnage by up to 500 kg.',
        recommendation: 'Request high-resolution flatbed rescan of original thermal ticket or obtain digital weighbridge server ledger printout.',
      },
      causality: {
        evidenceIds: ['EV-RECEIPT-001'],
        extractedFacts: [
          {
            label: 'Gross Weight',
            value: '28,400 kg',
            sourceRef: 'EV-RECEIPT-001',
          },
          {
            label: 'Tare Weight (Degraded)',
            value: '10,?00 kg',
            sourceRef: 'EV-RECEIPT-001',
          },
        ],
        modelOutputs: [
          {
            modelName: 'AWS Textract',
            outputKey: 'Tare Weight Confidence',
            score: 0.48,
            confidence: 0.48,
            caveat: 'Confidence below minimum threshold (0.75); triggers INCONCLUSIVE_DATA',
          },
        ],
        ruleResults: [
          {
            ruleId: 'RULE-ARITH-001',
            ruleName: 'Weight Arithmetic: Gross - Tare == Net',
            passed: false,
            expected: 'Gross (28,400) - Tare == Net (18,200)',
            actual: 'Tare weight character ambiguous due to fading',
            deviation: 'Cannot verify arithmetic with certainty',
          },
        ],
        inferences: [
          {
            statement: 'Thermal receipt degradation prevents autonomous confirmation of net tonnage.',
            basis: 'Low optical confidence in tare weight line item.',
          },
        ],
        uncertaintyScore: 0.65,
        recommendedHumanAction: 'Request high-resolution flatbed rescan of original thermal ticket or obtain weighbridge digital ledger log.',
      },
      createdAt: '2026-03-12T10:35:18Z',
    },
  ],
  'DOSSIER-BLR-2026-W14-018': [
    {
      id: 'FINDING-W14-001',
      dossierId: 'DOSSIER-BLR-2026-W14-018',
      title: 'Full Multimodal Compliance Verified',
      description: 'All submitted evidence items satisfy contractual, arithmetic, and spatial requirements. Net weight arithmetic verified exactly (24,000 - 9,500 = 14,500 kg).',
      category: 'RULE_RESULT',
      severity: 'CLEAN',
      modality: 'CROSS_MODAL',
      gagas: {
        criteria: 'All municipal desilting invoices must satisfy photo uniqueness, exact weighbridge arithmetic, and valid telemetry within the authorized quarry radius.',
        condition: 'All submitted artifacts pass automated verification: Photos are original, weighbridge arithmetic matches exactly, and GPS trajectory confirms disposal.',
        causeHypothesis: 'Contractor followed proper documentation and verification procedures.',
        effect: 'Dossier is clean and eligible for administrative payment certification.',
        recommendation: 'Adjudicate as VERIFIED_COMPLIANT and proceed with bill clearance.',
      },
      causality: {
        evidenceIds: ['EV-PHOTO-101', 'EV-RECEIPT-101'],
        extractedFacts: [
          { label: 'Gross Weight', value: '24,000 kg', sourceRef: 'EV-RECEIPT-101' },
          { label: 'Tare Weight', value: '9,500 kg', sourceRef: 'EV-RECEIPT-101' },
          { label: 'Net Weight', value: '14,500 kg', sourceRef: 'EV-RECEIPT-101' },
        ],
        modelOutputs: [
          {
            modelName: 'AWS Textract',
            outputKey: 'Receipt Clarity',
            score: 0.97,
            confidence: 0.97,
          },
        ],
        ruleResults: [
          {
            ruleId: 'RULE-ARITH-001',
            ruleName: 'Weight Arithmetic: Gross - Tare == Net',
            passed: true,
            expected: '24,000 - 9,500 == 14,500',
            actual: '14,500 kg',
          },
        ],
        inferences: [
          {
            statement: 'Evidence across photographic, document, and spatial modalities tells a consistent, compliant story.',
            basis: 'All deterministic rules passed and model confidence exceeds 0.95.',
          },
        ],
        uncertaintyScore: 0.02,
        recommendedHumanAction: 'Certify bill for payment.',
      },
      createdAt: '2026-03-10T14:20:00Z',
    },
  ],
  'DOSSIER-BLR-2026-W22-099': [
    {
      id: 'FINDING-W22-001',
      dossierId: 'DOSSIER-BLR-2026-W22-099',
      title: 'Inconclusive Evidence: Severe Optical Fading & GPS Telemetry Gap',
      description: 'Thermal receipt #89112 is faded below readable threshold (OCR confidence 0.44) and GPS telematics experienced sensor dropout during transit. Does NOT indicate wrongdoing.',
      category: 'MODEL_OUTPUT',
      severity: 'INCONCLUSIVE',
      technicalState: 'INCONCLUSIVE_DATA',
      modality: 'CROSS_MODAL',
      gagas: {
        criteria: 'Contract specifications require legible weighbridge receipts and continuous telematics logging during silt haulage.',
        condition: 'Thermal receipt has low OCR confidence (0.44) and telematics log has a 20-minute gap during transit.',
        causeHypothesis: 'Thermal printer failure and telematics cellular coverage dropout in Hebbal underpass.',
        effect: 'Insufficient evidentiary basis to either verify compliance or prove substantive inconsistency.',
        recommendation: 'Trigger REQUEST_RESCAN to obtain flatbed receipt scan and secondary telematics flash memory export.',
      },
      causality: {
        evidenceIds: ['EV-RECEIPT-201'],
        extractedFacts: [
          { label: 'Gross Weight (Faded)', value: '26,?00 kg', sourceRef: 'EV-RECEIPT-201' },
          { label: 'Tare Weight (Faded)', value: '10,?00 kg', sourceRef: 'EV-RECEIPT-201' },
        ],
        modelOutputs: [
          {
            modelName: 'AWS Textract',
            outputKey: 'Receipt Clarity',
            score: 0.44,
            confidence: 0.44,
            caveat: 'Confidence < 0.75 triggers INCONCLUSIVE_DATA; missing evidence != wrongdoing',
          },
        ],
        ruleResults: [
          {
            ruleId: 'RULE-ARITH-001',
            ruleName: 'Weight Arithmetic: Gross - Tare == Net',
            passed: false,
            expected: 'Gross - Tare == Net',
            actual: 'Inconclusive optical inputs',
          },
        ],
        inferences: [
          {
            statement: 'Evidentiary limitation prevents autonomous confirmation; auditor rescan required.',
            basis: 'Sensor dropout and optical degradation.',
          },
        ],
        uncertaintyScore: 0.78,
        recommendedHumanAction: 'Execute Request Rescan for flatbed scan of receipt #89112 and retrieve VTU offline flash memory.',
      },
      createdAt: '2026-03-14T09:15:00Z',
    },
  ],
};

// Default export alias for backward compatibility
export const DEMO_DOSSIER = BENCHMARK_DOSSIERS['DOSSIER-BLR-2026-W09-042'];
export const DEMO_EVIDENCE_ITEMS = BENCHMARK_EVIDENCE['DOSSIER-BLR-2026-W09-042'];
export const DEMO_FINDINGS = BENCHMARK_FINDINGS['DOSSIER-BLR-2026-W09-042'];
